#!/usr/bin/env bash

echo "Installing..."

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# Aliases
rm -rf $HOME/.bash_aliases
ln -s $DOTFILES/.bash_aliases $HOME/.bash_aliases

# Script setup-laravel
rm -rf $SCRIPTS/setup-laravel.sh
ln -s $DOTFILES/scripts/setup-laravel.sh $SCRIPTS/setup-laravel.sh

# Script remove-laravel
rm -rf $SCRIPTS/remove-laravel.sh
ln -s $DOTFILES/scripts/remove-laravel.sh $SCRIPTS/remove-laravel.sh

# Setup VS Code configs
bash $DOTFILES/scripts/install-vscode-setup.sh

# Toggle laptop monitor scripts
rm -rf $SCRIPTS/toggle-laptop-monitor.sh
ln -s $DOTFILES/scripts/toggle-laptop-monitor.sh $SCRIPTS/toggle-laptop-monitor.sh

echo "Instalation done!"

