#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# Setup terminal
# ---------------------------------------------------------------------------------------------------
# Generate new uuid
UUID=$(uuidgen)

# Get list of current profiles
CURRENT_PROFILES=$(dconf read /org/gnome/terminal/legacy/profiles:/list)

# Add new uuid to the list of profiles
if [ -z "$CURRENT_PROFILES" ]; then
UPDATED_PROFILES="['$UUID']"
else
UPDATED_PROFILES=$(echo "$CURRENT_PROFILES" | sed "s/\]$/,'$UUID']/")
fi

# Load updated list to profiles
dconf write /org/gnome/terminal/legacy/profiles:/list "$UPDATED_PROFILES"

# Make new profile defualt
dconf write /org/gnome/terminal/legacy/profiles:/default "'$UUID'"

# Copy terminal settings to tmp location
cp $DOTFILES/terminal-settings.conf /tmp/terminal-settings.conf

# Add new uuid to terminal settings
sed -i "s/NEW_UUID/$UUID/" /tmp/terminal-settings.conf

# Load terminal configuration
dconf load /org/gnome/terminal/ < /tmp/terminal-settings.conf

# Remove temporary file
rm -rf /tmp/terminal-settings.conf
# ---------------------------------------------------------------------------------------------------

# Setup aliases
# ---------------------------------------------------------------------------------------------------
rm -rf $HOME/.bash_aliases
ln -s $DOTFILES/.bash_aliases $HOME/.bash_aliases
# ---------------------------------------------------------------------------------------------------
